[package]
name = "rules-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
mlua = { version = "0.10.3", features = ["serialize", "lua54", "vendored"] }
rusqlite = "0.32.0"
sea-query = "0.32.1"
sea-query-rusqlite = "0.7.0"
serde = { version = "1.0.217", features = ["derive"] }
strum = { version = "0.27.0", features = ["derive"] }
thiserror = "2.0.11"
native_db = "0.8.1"
native_model = "0.6.1"
bincode = "1.3.3"
termtree = "0.5.1"
pak-db = "0.1.1"
