[package]
name = "src-database"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.210", features = ["derive"] }
sled = "0.34.7"
vitruvian-types = { path = "../src-types" }
